const fs = require('fs');
let code = fs.readFileSync('artifacts/paradox-ticket/src/App.tsx', 'utf8');

const lines = code.split('\n');
const studioIndex = lines.findIndex(l => l.startsWith('function Studio({ admin = false'));

if (studioIndex !== -1) {
  lines[studioIndex] = `function Studio({ admin = false }: { admin?: boolean }) { const [tab, setTab] = useState('Venues'); return <Shell><section className="mx-auto max-w-[1180px] px-5 py-16 md:px-10 md:py-24"><span className="mono-label text-[10px] text-accent">{admin ? 'Back office / Paradox' : 'Organiser studio / June 2025'}</span><h1 className="display-font mt-4 text-8xl leading-[.8]">{admin ? <>Keep the<br /><i>house ready.</i></> : <>Good nights<br /><i>add up.</i></>}</h1>{admin ? <><div className="mt-14 flex gap-6 border-b border-foreground/15">{['Venues', 'Seat layouts', 'Support tickets'].map(t => <button key={t} onClick={() => setTab(t)} className={\`pb-4 text-sm \${tab === t ? 'border-b-2 border-accent text-accent' : 'text-foreground/50'}\`} data-testid={\`button-tab-\${t}\`}>{t}</button>)}</div><div className="mt-8 border border-foreground/15 bg-card p-7"><h2 className="display-font text-4xl">{tab === 'Venues' ? 'The Rivington' : tab}</h2><p className="mt-3 text-sm text-foreground/55">{tab === 'Venues' ? '120 seats · New York' : 'Manage the details that keep the room ready.'}</p><button className="mt-8 border border-foreground/20 px-4 py-3 text-xs font-semibold" data-testid="button-admin-action">Edit {tab.toLowerCase()}</button></div></> : <div className="mt-14 flex gap-6 border-b border-foreground/15">{['Overview', 'Support tickets'].map(t => <button key={t} onClick={() => setTab(t)} className={\`pb-4 text-sm \${tab === t ? 'border-b-2 border-accent text-accent' : 'text-foreground/50'}\`}>{t}</button>)}</div>}{tab === 'Overview' ? <><div className="mt-8 grid gap-px border border-foreground/15 bg-foreground/15 sm:grid-cols-2 lg:grid-cols-4">{[['Gross revenue', '?17,10,000'], ['Tickets moved', '684'], ['Sell-through', '87.6%'], ['Avg. ticket', '?2,500']].map(([l, v]) => <div key={l} className="bg-card p-6"><span className="mono-label text-[9px] text-foreground/45">{l}</span><p className="mt-5 text-3xl font-semibold">{v}</p><span className="mt-2 block text-xs text-accent">+12.4% from last month</span></div>)}</div><div className="mt-10 border border-foreground/15 bg-card p-8"><span className="mono-label text-[10px] text-foreground/45">Tonight's room</span><h2 className="display-font mt-4 text-5xl">Arijit Singh Live</h2><p className="mt-5 text-sm text-foreground/55">112 of 120 seats booked · ?2,80,000 gross</p></div></> : null}</section></Shell>; }`;
}

fs.writeFileSync('artifacts/paradox-ticket/src/App.tsx', lines.join('\n'));
